eslint.config.js, package-lock.json, package.json, src/App.tsx
eslint.config.js : 기존 내용 분석해서 필요한 부분 가져와서 수정하고 다시 올려야 할 듯
=> [feat] add library (emotion, eslint, recoil, react-query)

eslint.config.js, package-lock.json, package.json, src/App.tsx
=> [feat] packages init

eslint.config.js, src/App.tsx, src/layout/Mainlayout.tsx, src/layout/SearchBar.tsx, src/main.tsx, src/pages/Result.tsx, src/router/index.tsx
=> [feat] mainLayout / navigation init

index.html
=> [add] site name change

src/layout/CardList.tsx, src/pages/Home.tsx, src/utils/ScoreToImage.ts
feat/#1-component-architecture -> develop
대소문자 이슈 픽스
=> [fix] import 대소문자 이슈 해결

package-lock.json, package.json, src/components/Header.tsx, src/components/SearchBar.tsx, src/layout/Card/Card.Style.ts, src/layout/Card/Card.tsx, src/layout/CardList/CardList.tsx, src/layout/Mainlayout.tsx, src/pages/Home.tsx, yarn.lock
feat/#1 component architecture -> develop
- 간단한 CSS 적용 및 디렉토리 구조 개펀
- 공용 디자인 컴포넌트를 위한 styles 디렉토리 추가
- @emotion/styled 패키지 추가
=> #1 Feat/#1 component architecture

src/layout/Card/Card.tsx, src/layout/CardList/CardList.tsx, src/pages/Home.tsx, src/ts/Interfaces.ts
feat/#15-home-component - > devlop
종목명(stockName) 추가
=> #15 [feat] Home 화면 카드 종목명 추가

eslint.config.js, package-lock.json, package.json
feat/#15 -> deveelop
Peer dependencies 충돌로 인한 eslint-airbnb 패키지 삭제
=> #15 [fix] esint airbnb 제거

src/pages/Home/Home.Style.ts, src/pages/Home/Home.tsx
=> #15 [fix] 배포 오류 검증

src/layout/Card/Card.Style.ts, src/layout/Card/Card.tsx, src/layout/HotCard/HotCard.Style.ts, src/pages/Home/Home.Style.ts, src/pages/Home/Home.tsx
Feat/#15 home component -> develop
인기 종목 컴포넌트 반응형 구현
=> #15 [feat] 반응형 구현

src/layout/HotCard/HotCard.Style.ts, src/layout/HotCard/HotCard.tsx
Feat/#15 home component -> develop
디자인 수정
- 인기종목 내부 컴포넌트 비율 조정
=> #15 [feat] 디자인 수정

src/layout/HotCard/HotCard.tsx
Feat/#15 home component -> devolop
미사용 import 제거
=> #15 [fix] 미사용 import 제거

src/layout/Mainlayout/Mainlayout.tsx, src/pages/Home/Home.Style.ts
Feat/#15 home component -> dev
mainLayout 패딩 삭제 
=> #15 [feat] 홈화면 디자인 수정

src/layout/HotCard/HotCard.Style.ts, src/pages/Home/Home.Style.ts, src/pages/Home/Home.tsx
Feat/#15 home component -> dev
미사용 스타일 컴포넌트 삭제
API 세팅 준비
홈화면 하단 패딩 추가
=> #15 [feat] 디자인 마이너 수정 및 API 세팅 준비

src/components/Header.tsx, src/layout/Card/Card.Style.ts, src/layout/HotCard/HotCard.Style.ts, src/pages/Home/Home.Style.ts, src/pages/Home/Home.tsx, src/services/api.ts
Feat/#15 home component-> dev
카드 리스트 width, height 조절
=> #15 [feat] 디자인 반영

index.html
=> #15 [feat] 앱로고 추가

src/components/Footer/Footer.tsx, src/controllers/api.ts, src/layout/CardList/CardList.Style.ts, src/layout/HotCard/HotCard.Style.ts, src/layout/Mainlayout/Mainlayout.Style.ts, src/pages/Home/Home.Style.ts
Feat/#15 home component -> dev
styledComponents 객체 형태로 수정
=> #15 [refactor] styledComponents 객체 형태로 수정

index.html
feat/#37-search-result-component -> develop
api 통신 해결
=> #37 [fix] api https->http

src/components/StockSlotMachine/stockSlotMachine.Style.ts, src/layout/HotCard/HotCard.Style.ts, src/pages/Home/Home.tsx
- [x ] 기능 추가
Feat/#15 home component -> dev
디자인 반영 컴포넌트 수정
=> #15 [feat] 디자인 반영 컴포넌트 수정

src/components/StockWordCloud/StockWordCloudWorker.ts
feat/#66-stock-word-cloud -> develop
=> #66 [feat] WordCloud Worker Prop 수정

src/components/SearchBar/SearchBar.Prop.ts
=> #75 [feat] API 단일화2

public/index.html, vite.config.ts
[feat] Google Analytics 수정 -> dev
=> #75 [feat] Google Analytics 수정

package.json
=> #89 [feat] 반응형 초기구현

tsconfig.json
=> #89 [feat] pwa 구현중

netlify.toml
=> #89 [feat] netlify 설정 수정

vite.config.ts
=> #89 [feat] plugin 수정

dev-dist/registerSW.js, index.html, netlify.toml, package-lock.json, package.json, public/index.html, vite.config.ts, yarn.lock
=> #89 [feat] netlify.toml 수정

src/components/RelatedStock/RelatedStock.tsx, src/index.css, src/pages/Search/Search.tsx, src/router/index.tsx
feat/#107-related-stock-component -> develop
=> #107 [feat] 종목 클릭시 이동 구현

src/layout/CardList/CardList.Style.ts
feat/#15 -> dev
화살표 수직 가운데 정렬
=> #15 [feat] 홈화면 카드리스트 화살표 위치 변경

src/layout/CardList/CardList.tsx, src/pages/Home/Home.tsx
=> #15 [feat] 레이지로딩을 통한 렌더링 최적화

src/layout/Card/Card.Style.ts, src/layout/Card/Card.tsx, src/layout/CardList/CardList.tsx, src/pages/Home/Home.tsx, src/ts/Interfaces.ts
=> #15 [feat] 점수 등락 구현 중

src/main.tsx, src/pages/Home/Home.tsx, src/queryClient.ts, src/ts/Types.ts
feat/#88-> dev
react-query 관련 홈화면 리팩토링
=> #88 [refactor] react-query 관련 홈화면 리팩토링

package-lock.json, package.json, src/hooks/useStocks.ts, src/pages/Home/Home.tsx, src/router/index.tsx, yarn.lock
=> #88 에러 핸들링 추가

src/components/Common/Common.Props.ts, src/components/Common/Common.Type.ts, src/components/StockSlotMachine/StockSlotMachine.tsx, src/components/StockSlotMachine/stockSlotMachine.Style.ts, src/layout/HotCard/HotCard.tsx, src/pages/Search/Search.tsx
ex) feat/#64-stock-slot-machine -> develop
슬롯머신 애니메이션 수정
컴포넌트 재사용을 위한 분리
새로운 transition 함수 적용
=> #64 [feat] 슬롯머신 애니메이션 수정

src/components/StockWordCloud/StockWordCloud.Style.ts, src/components/StockWordCloud/StockWordCloudWorker.ts
ex) feat/#66-stock-word-cloud -> develop
다른 브라우저에서 폰트 깨지는 현상 수정
- 사파리는 아직 테스트 더 해봐야 할 듯
=> #66 [feat] 워드클라우드 폰트 적용

src/layout/CardList/CardList.Style.ts, src/layout/CardList/CardList.tsx, src/router/index.tsx
feat/#88 -> dev
로딩 화면 및 에러 처리 지역화
=> #88 [refactor] 로딩 화면 및 에러 처리 지역화

src/components/SearchBar/SearchBar.Props.ts, src/components/SearchBar/SearchBar.Style.ts, src/components/SearchBar/SearchBar.tsx
feat/#128-autocomplete-event -> develop
검색어 키보드로 이동해서 입력 기능 구현
=> #128 [feat] 검색창 키보드 이벤트 구현 및 리팩토링

src/layout/CardList/CardList.tsx, src/pages/Home/Home.Style.ts, src/pages/Home/Home.tsx
feat/#90-overall-refactor -> develop
홈화면 국내/해외 탭 메뉴 디자인 반영
=> #90 [feat] 국내 해외 탭 디자인 피드백 반영

src/hooks/useStocks.ts, src/layout/CardList/CardList.tsx, src/pages/Home/Home.tsx, src/queryClient.ts
feat/#88 -> dev
에러처리 각각의 컴포넌트로 분리
=> #88 [refactor] 에러처리 각각의 컴포넌트로 분리

src/layout/CardList/CardList.tsx
Feat/#15-> dev
obeserver iterator 변경
=> #15 [refactor] obeserver iterator 변경

src/components/StockCard/StockCard.Style.tsx, src/components/StockCard/StockCard.tsx, src/controllers/api.ts, src/layout/CardList/CardList.tsx
=> #15 [feat] 떡상/떡락 지표 디자인 수정

src/components/SearchTitle/SearchTitle.Syle.ts, src/components/SearchTitle/SearchTitle.tsx, src/components/StockSlotMachine/StockSlotMachine.tsx, src/controllers/api.ts, src/controllers/query.ts, src/pages/Search/Search.tsx, src/styles/keyframes.ts
feat/#37-search-result-component -> develop
검색 결과 상세페이지 디자인 반영
- 주식 번호, 코스피/코스닥, 가격
검색 타이틀 길어지면 애니메이션 효과 적용
=> #37 [feat] 상세페이지 타이틀 디자인 반영 및 애니메이션 추가

src/components/CardList/CardList.Style.ts, src/components/CardList/CardList.tsx
=> #15 홈화면 버튼 수정

src/components/PopUp/ZipyoPopUp.style.ts, src/components/PopUp/ZipyoPopUp.tsx, src/pages/Search/Search.tsx
=> #37 [feat] 지표 팝업 구현

src/components/PopUp/ZipyoPopUp.style.ts, src/components/PopUp/ZipyoPopUp.tsx
=> #37 [feat] 지표 팝업 점수 폰트크기 수정

src/components/PopUp/AntVoicePopUp.style.ts, src/components/PopUp/AntVoicePopUp.tsx, src/components/SearchTitle/SearchTitle.tsx, src/controllers/api.Type.ts, src/pages/Search/Search.tsx
=> #37 [feat] 개미들의 목소리 팝업 및 리팩토링

src/components/PopUp/ZipyoPopUp.style.ts
=> #37 [feat] 지표 팝업 이미지 높이 수정

src/components/SearchBar/SearchBar.tsx
feat/#34 -> dev
자동완성 국내/해외 종목 구현
=> #34 [feat] 자동완성 국내/해외 종목 구현

src/components/SearchTitle/SearchTitle.tsx, src/controllers/api.ts
=> #37 [feat] 종목 주가 / 변동폭 임시 구현

src/components/SearchTitle/SearchTitle.tsx
=> #37 [feat] 종목 주가 / 변동폭 API 연동

src/components/PopUp/AntVoicePopUp.style.ts, src/components/PopUp/AntVoicePopUp.tsx, src/components/PopUp/ZipyoPopUp.style.ts, src/components/PopUp/ZipyoPopUp.tsx
=> #34 [feat] 팝업화면 반응형 구현

src/components/PopUp/AntVoicePopUp.style.ts, src/components/SearchTitle/SearchTitle.Style.ts
=> #37 [feat] 모바일 폰트 줄임

index.html
=> #15 [feat] 모바일 검색 확대 방지

src/components/CardList/CardList.tsx, src/components/MobileStockCard/MobileStockCard.Style.tsx, src/components/MobileStockCard/MobileStockCard.tsx, src/controllers/api.ts, src/pages/Home/Home.tsx
=> #15 [feat] 모바일 반응형 구현

src/components/CardList/CardList.tsx, src/components/MobileStockCard/MobileStockCard.tsx
feat/#15 -> dev
API 호출 후 화면 이동하도록 수정
=> #15 [feat]  API 호출 후 화면 이동하도록 수정

src/components/CardList/CardList.tsx, src/components/MobileStockCard/MobileStockCard.tsx
=> #15 [refactor] 종목 리스트 리팩토링

src/components/SearchBar/SearchBar.Props.ts, src/components/SearchBar/SearchBar.tsx, src/pages/Search/Search.tsx
- [x] 기능 추가
feat/#34 -> dev
최근 검색 기록 디벨롭
=> #34 [feat] 최근 검색 기록 디벨롭

src/components/CardList/CardList.Style.ts, src/components/CardList/CardList.tsx, src/components/MobileStockCard/MobileStockCard.tsx, src/components/SearchBar/SearchBar.tsx, src/components/StockCard/StockCard.tsx, src/components/StockSlotMachine/StockSlotMachine.tsx
=> #15 [fix] 상세페이지 이동 버그 픽스

src/components/CardList/CardList.tsx
=> #15 [fix] 렌더링 관련 useCallback 삭제

src/components/CardList/CardList.Style.ts, src/components/CardList/CardList.tsx, src/components/MobileStockCardGrid/MobileStockCardGrid.tsx, src/hooks/useIsMobile.ts, src/pages/Search/Search.tsx, src/utils/chunkArray.ts
=> #15 [feat] 관련종목 및 반응형 리팩토링

src/pages/Home/Home.tsx
=> #89 [test] PWA 업데이트 확인

src/main.tsx, src/pages/Home/Home.tsx
=> #89 [test] 업데이트 확인 테스트

src/components/CardList/CardList.Style.ts, src/components/CardList/CardList.tsx
=> #15 [feat] 인디케이터 구현

src/components/ErrorComponent.tsx, src/components/PopUp/AntVoicePopUp.style.ts, src/components/PopUp/AntVoicePopUp.tsx, src/components/PopUp/ZipyoPopUp.tsx, src/components/SearchBar/SearchBar.tsx, src/controllers/api.Type.ts, src/controllers/mock.ts, src/controllers/query.ts, src/pages/Home/Home.tsx, src/pages/Search/Search.tsx
=> #37 팝업 컴포넌트 수정

src/components/SearchBar/SearchBar.tsx
=> #37 [fix] 최근 검색 기록 버그픽스

index.html, src/components/SearchBar/SearchBar.tsx, src/controllers/api.ts
=> #37 [test] 테스트용 목데이터 추가

src/components/CardList/CardList.tsx, src/pages/Home/Home.tsx
=> #15 [fix] 인디케이터 버그 수정

src/components/CardList/CardList.Style.ts, src/components/CardList/CardList.tsx
=> #15 [feat] 애로우버튼 고도화 반복 가능

src/components/PWAUsage/iOSSafari/IOSSafari.style.ts, src/components/PWAUsage/iOSSafari/IOSSafari.tsx, src/pages/Usage/Usage.Style.ts
feat/#89-> dev
하단 공백 제거 및 스타일링 수정
=> #89 [feat] 하단 공백 제거 및 스타일링 수정

src/components/PopUp/ZipyoPopUp.tsx
=> #37 [feat] 닫기 버튼 수정

src/components/CardList/CardList.tsx, src/components/MobileStockCard/MobileStockCard.tsx, src/components/MobileStockCardGrid/MobileStockCardGrid.tsx, src/components/SearchBar/SearchBar.tsx, src/components/StockCard/StockCard.tsx, src/components/StockSlotMachine/StockSlotMachine.tsx, src/controllers/api.ts, src/controllers/query.ts, src/pages/Search/Search.tsx
=> #90 [feat] 검색에 country 매개변수 추가

src/pages/Home/Home.tsx, src/pages/Usage/Usage.tsx, src/utils/Detector.ts
PWA 인 경우, 팝업 오픈 X
사용법 본 경우 5분간 팝업 오픈 X
=> #90 [feat] PWA 앱 고도화

.prettierrc, src/components/StockChart/StockChart.Style.ts, src/components/StockChart/StockChart.tsx, src/components/StockChart/StockChartCanvas.tsx, src/controllers/api.ts, src/pages/Search/Search.tsx
ex) feat/#111-stock-chart-component   -> develop
컴포넌트 세부화 및 최적화 리팩토링 진행중
=> #111 [refactor] 차트 컴포넌트 리팩토링

src/components/CardList/CardList.tsx, src/components/MobileStockCard/MobileStockCard.Style.tsx, src/components/MobileStockCard/MobileStockCard.tsx, src/pages/Home/Home.tsx
=> #90 [feat] 홈화면 구성 변경

src/components/MobileStockCard/MobileStockCard.Style.tsx, src/pages/Home/Home.Style.ts, src/pages/Home/Home.tsx
=> #90 [feat] 지수 인덱스 추가

src/components/StockChart/StockChart.Style.ts, src/components/StockChart/StockChart.tsx, src/components/StockChart/StockChartCanvas.tsx
feat/#111-stock-chart-component -> develop
차트 로직 최적화
화면 사이즈에 따른 반응형 스타일 적용
모바일 터치 이벤트 적용
=> #111 [feat] 반응형 이벤트 추가

src/components/StockChart/StockChart.Style.ts, src/components/StockChart/StockChart.tsx, src/components/StockChart/StockChartCanvas.tsx
feat/#111-stock-chart-component -> develop
이동평균선 구현
최적화(진행중)
=> #111 [feat] 이동평균선 추가

src/components/MobileStockCard/MobileStockCard.tsx
ex) develop-> main
운영계 배포를 위한 PR
- 미구현 기능 목데이터 (해시태그) 삭제
=> #90 [fix] 운영계 배포용 핫픽스(해시태그 삭제)

src/components/CardList/CardList.Style.ts, src/components/CardList/CardList.tsx, src/components/MobileStockCard/MobileStockCard.Style.tsx, src/components/MobileStockCard/MobileStockCard.tsx, src/components/StockCard/StockCard.Style.tsx, src/pages/Home/Home.Style.ts, src/pages/Home/Home.tsx, src/styles/themes.ts
=> #90 [feat] 모바일 홈화면 디자인 수정

src/components/MobileStockCard/MobileStockCard.Style.tsx, src/controllers/api.ts, src/controllers/query.ts, src/pages/Home/Home.Style.ts, src/pages/Home/Home.tsx
=> #15 [feat] 지수지표 목데이터로 구현

src/pages/Home/Home.Style.ts, src/pages/Home/Home.tsx
=> #15 [feat] 지수 지표 수정

src/components/MobileStockCard/MobileStockCard.Style.tsx, src/pages/Home/Home.Style.ts
=> #15 [feat] 지수 지표 디자인 수정

src/components/Common/ContentsItem.Style.ts, src/pages/Home/Home.Style.ts, src/pages/Home/Home.tsx
=> #15 [feat] 산출 기준일 표기

src/components/StockCard/StockCard.Style.tsx, src/components/StockCard/StockCard.tsx
=> #15 [feat] 웹 카드리스트 고도화

src/components/StockTable/StockTable.style.ts, src/pages/Home/Home.Style.ts
=> #15 [feat] 산출 기준 일자 디자인 수정

src/components/CardList/CardList.Style.ts, src/components/CardList/CardList.tsx
=> #15 [feat] 홈화면 고도화

src/components/Keywords/Keywords.style.tsx, src/components/Keywords/Keywords.tsx, src/components/MobileStockCard/MobileStockCard.Style.tsx, src/components/StockTable/StockTable.style.ts, src/components/StockTable/StockTable.tsx, src/pages/Home/Home.tsx
=> #15 [feat] 키워드 컴포넌트 구현

src/components/Keywords/Keywords.tsx, src/components/StockTable/StockTable.style.ts
=> #15 [feat] 키워드 폰트사이즈 수정

src/components/Keywords/Keywords.tsx, src/components/StockTable/StockTable.tsx, src/controllers/api.Type.ts, src/controllers/api.ts, src/controllers/mock.ts, src/controllers/query.ts
=> #15 [feat] 종목차트별 인간지표 및 키워드 목데이터 연결

src/components/Keywords/Keywords.tsx, src/components/StockTable/StockTable.tsx, src/controllers/api.ts, src/controllers/query.ts, src/pages/Home/Home.tsx
종목차트별 인간지표 및 키워드 국내/해외 파라미터 추가
=> #15 [feat] 종목차트별 인간지표 및 키워드 국내/해외 파라미터 추가

src/components/IndexScore/IndexScore.tsx, src/components/Keywords/Keywords.tsx, src/components/StockTable/StockTable.tsx
feat#15 -> dev
지수인간지표, 종목차트별 인간지표 키워드
로딩 및 에러처리 추가
이 커밋을 마지막으로 고도화 브랜치에서 작업할겠습니다
=> #15 [feat] 로딩 및 에러처리 추가

src/components/CardList/CardList.tsx
=> #219 [feat] 인디케이터 고도화

src/components/PopUp/PWAinfoPopUp/PWAinfoPopUp.style.ts, src/components/StockTable/StockTable.style.ts
=> #219 [feat] 디자인 마이너 수정

src/components/PopUp/ZipyoPopUp/ZipyoPopUp.style.ts, src/components/PopUp/ZipyoPopUp/ZipyoPopUp.tsx
=> #219 [feat] 지표 팝업 폰트 사이즈 수정

src/components/MobileStockCard/MobileStockCard.tsx, src/components/PopUp/CommonPopUp.style.ts, src/components/PopUp/KeywordPopUp/KeywordPopUp.tsx
=> #219 [feat] 홈화면 및 카드 일부 수정

src/components/Keywords/Keywords.tsx, src/components/StockTable/StockTable.tsx, src/pages/Home/Home.tsx
=> #219 [feat] 업데이트 시각 텍스트 수정

src/components/Footer/Footer.tsx
=> #44 [fix] linkedinSVG 오탈자 수정

src/components/IndexScore/IndexScore.tsx, src/components/StockTable/StockTable.style.ts, src/components/StockTable/StockTable.tsx
=> #219 [feat] 종목차트별 인간지표 반응형 구현

src/components/Keywords/Keywords.style.tsx, src/components/StockTable/StockTable.style.ts, src/components/StockTable/StockTable.tsx
키워드 모바일 폰트 수정
stockTable 스타일 수정
=> #219 [feat] 키워드 및 종목차트 수정

src/components/MobileStockCard/MobileStockCard.Style.tsx, src/components/StockSlotMachine/stockSlotMachine.Style.ts, src/pages/Search/Search.tsx
=> #37 [feat] 관련 종목 수정

src/components/StockSlotMachine/stockSlotMachine.Style.ts
=> #37 [feat] 홈화면 sideeffect 제거

index.html, src/App.css, src/App.tsx
=> #37 [feat] 폰트 전역 설정

src/components/Footer/Footer.Style.ts, src/components/Footer/Footer.tsx
=> #90 [refactor] 푸터 아이콘 수정

src/components/Component.style.tsx, src/components/IndexScore/IndexScore.tsx
feat/#120 -> dev
로딩 및 에러처리 모바일 반응형 구현
=> #120 [feat] 로딩 및 에러처리 반응형 구현

src/components/PopUp/CommonPopUp.style.ts, src/components/PopUp/FearPopUp/FearPopUp.tsx, src/controllers/api.ts, src/controllers/query.ts, src/pages/Home/Home.tsx, src/ts/Constants.ts
=> #90 [refactor] 공포지수 팝업 멘트 추가 및 상수 관련 리팩토링

.github/workflows/static.yml
feat/#220 -> dev
configure-page 버전
4 -> 5
=> #220 [feat] configure-page 버전 수정

src/components/SearchBar/SearchBar.Style.ts, src/components/SearchBar/SearchBar.tsx
=> #90 [feat] 검색바 고도화

src/utils/ScoreConvert.ts
=> #90 [feat] 점수 구간 수정

src/components/IndexScore/IndexScore.style.ts, src/components/MobileStockCard/MobileStockCard.Style.tsx, src/components/SearchTitle/SearchTitle.Style.ts, src/components/SearchTitle/SearchTitle.tsx, src/components/StockCard/StockCard.Style.tsx, src/components/StockTable/StockTable.style.ts, src/utils/ScoreConvert.ts
feat/#90  -> dev
deltaScoreToColor 함수로 리팩토링
=> #90 [refactor] 점수 변동폭 색상 함수 분리

src/components/MobileStockCard/MobileStockCard.tsx, src/components/StockCard/StockCard.Style.tsx, src/components/StockCard/StockCard.tsx, src/utils/ScoreConvert.ts
=> #90 [feat] 점수 표기 고도화

src/components/IndexScore/IndexScore.tsx, src/controllers/api.Type.ts, src/controllers/api.ts, src/controllers/mock.ts, src/controllers/query.ts
=> #219 [feat] 지수 인간지표 점수 API 연결

src/components/CardList/CardList.tsx, src/components/MobileStockCard/MobileStockCard.tsx, src/components/StockCard/StockCard.tsx, src/components/StockTable/StockTable.tsx, src/controllers/api.Type.ts, src/controllers/api.ts, src/controllers/query.ts, src/pages/Search/Search.tsx, src/ts/Interfaces.ts
=> #219 [feat] API 연결

src/components/CardList/CardList.tsx, src/components/StockTable/StockTable.tsx, src/hooks/useStocks.ts, src/pages/Search/Search.tsx, src/ts/Interfaces.ts
=> #219 [feat] 종목차트별 인간지표 클릭시 검색 기능 구현

src/components/CardList/CardList.tsx, src/components/PopUp/AntiVoicePopUp/AntVoicePopUp.style.ts, src/components/PopUp/AntiVoicePopUp/AntVoicePopUp.tsx
feat/#90 -> dev
인디케이터 삭제
개미들의 목소리 팝업 수정
=> #90 [feat] 전반적 QA 반영

src/components/StockTable/StockTable.tsx
종목 차트별 인간지표 텍스트 수정
거래대금 -> 시가총액
=> #90 [feat] 종목 차트별 인간지표 텍스트 수정

src/components/StockWordCloud/StockWordCloud.tsx, src/utils/worker/GenerateWordCloud.ts
feat/#66-stock-word-cloud -> develop
fontsize 로 인한 measuretext 오작동 문제 해결
=> #66 [fix] offscreen canvas fontsize 에러 해결

src/components/Keywords/Keywords.tsx
=> #219 [feat] 키워드 텍스트 수정

index.html
=> #90 [feat] 타이틀 수정

src/components/StockChart/StockChart.tsx
feat/#111-stock-chart-component -> develop
모바일환경 하단 차트 제목 추가 
점수 표시 인디케이터 조정(100,50,0) => 줌인줌아웃 됨 참고로
=> #111 [feat] 하단 차트 제목 추가 및 인디케이터 조정

src/components/Search/StockWordCloud/StockWordCloud.Worker.ts, wasm/wordcloud.c
=> #90 [fix] wordCloud 경로수정

src/pages/Usage/Usage.tsx
PWA 화면 수정
일단 다 ios / safari 기준
=> #90 [feat] PWA 화면 수정

src/controllers/api.Type.ts, src/controllers/mock.ts, src/pages/Home/Home.tsx
=> #90 [feat] interface 내 미사용 멤버 제거

src/components/SearchBar/SearchBar.Style.ts, src/components/SearchBar/SearchBar.tsx
feat/#254-keyword-search -> develop
종목 검색 결과 symbol 추가
- symbol, 거래소 추가
- symbol 자동완성 효과 적용
=> #254 [feat] 검색창 symbol 추가

src/components/Home/Keywords/Keywords.tsx, src/components/PopUp/FearPopUp/FearPopUp.tsx, src/components/StockSlotMachine/StockSlotMachine.tsx, src/components/StockSlotMachine/stockSlotMachine.Style.ts
=> #90 [feat] 홈화면 수정

src/components/SearchBar/SearchBar.tsx, src/controllers/query.ts, src/utils/worker/GenerateWordCloud.ts
feat/#66-stock-word-cloud -> develop
FireFox 브라우저 호환성 체크 => Chrome과 동일
=> #66 [fix] FireFox 브라우저 호환성 체크

eslint.config.js, src/components/CardList/StockCard/StockCard.tsx, src/components/Search/SearchTitle/SearchTitle.Style.ts, src/components/Search/SearchTitle/SearchTitle.tsx, src/controllers/api.Type.ts, src/controllers/api.ts, src/controllers/mock.ts, src/controllers/query.ts, src/pages/Search/Search.tsx
feat/#37-search-result-component -> develop
종목 요약 내용 API 적용 -> SearchTitle 컴포넌트
리스트로 넘어온 텍스트 column으로 적용
=> #37 [feat] 종목 요약 내용 api 적용

src/components/CardList/CardList.tsx, src/components/Home/IndexScore/IndexScore.tsx, src/components/Home/Keywords/Keywords.tsx, src/components/Home/StockTable/StockTable.tsx, src/components/SearchBar/SearchBar.tsx, src/controllers/api.Type.ts, src/controllers/api.ts, src/controllers/query.ts, src/hooks/useQuery.tsx, src/pages/Search/Search.tsx
=> #90 [refactor] useQurey 리팩토링

src/components/CardList/CardList.tsx, src/components/CardList/StockCard/StockCard.Style.tsx, src/components/StockSlotMachine/StockSlotMachine.tsx, src/components/StockSlotMachine/stockSlotMachine.Style.ts
=> #90 [feat] 인기 지표 점수변화 추가

src/components/Common/ContentsItem.Style.ts, src/components/Home/IndexScore/IndexScore.style.ts, src/components/Home/StockTable/StockTable.style.ts, src/components/Home/StockTable/StockTable.tsx, src/components/Search/StockChart/StockChart.Style.ts, src/components/Search/StockChart/StockChart.tsx, src/components/SearchBar/SearchBar.Style.ts, src/components/StockSlotMachine/StockSlotMachine.tsx, src/components/StockSlotMachine/stockSlotMachine.Style.ts, src/layout/Footer/Footer.Style.ts, src/layout/Footer/Footer.tsx, src/pages/Home/Home.Style.ts, src/pages/Home/Home.tsx, src/pages/Search/Search.Style.ts
feat/#90-overall-refactor -> develop
슬롯머신 컴포넌트 디자인 변경
전체적인 gap, padding 수정
Footer 텍스트 삭제
=> #90 [feat] 전반적인 디자인 반영

.emotionorderrc, .prettierrc, package-lock.json, package.json, src/components/Event/Disquiet.Style.ts, src/components/Home/IndexScore/IndexScore.style.ts, src/components/Home/Keywords/Keywords.style.tsx, src/components/Search/StockChart/StockChart.Style.ts, src/components/Search/StockChart/StockChart.tsx, src/controllers/query.ts, yarn.lock
feat/#34-search-bar -> develop
이동평균선 버그 발견
: 무지성 ~~때문에 소숫점 버려서 생긴 문제였음
Number함수로 변경
=> #111 [fix] 이동평균선 정수 -> 유리수 변경

src/pages/Home/Home.Style.ts, src/pages/Home/Home.tsx, yarn.lock
feat/#90-overall-refactor -> develop
탭 선택시 색 안바뀌는 문제 -> 탭 메뉴 className 해결
=> #90 [fix] tab 메뉴 색 안바뀌는 현상 해결

src/components/Search/StockChart/StockChart.tsx, src/controllers/query.ts
feat/#111-stock-chart-component
마우스위치 스톡차트 그리는 함수에 DPR 적용 안해놔서 고침
=> #111 [fix] 맥북 차트 마우스 위치 이상 현상 해결

.prettierrc, src/components/Search/SearchTitle/SearchTitle.Style.ts, src/components/Search/SearchTitle/SearchTitle.tsx, src/layout/Header/Header.Style.ts, src/layout/Header/Header.tsx
feat/#37-search-result-component -> develop
상세페이지 Title 애니메이션 버벅임 해결
=> #37 [fix] Title 애니메이션 버벅임 해결

src/components/Search/SearchTitle/SearchTitle.tsx, src/components/Search/StockChart/StockChart.tsx
feat/#111-stock-chart-component -> develop
트랙패드에서 줌기능 사용할 경우 속도가 너무 빠른 부분 해결
-> scroll이벤트에서 deltay 값 기반으로 변경
-> 일반 마우스 스크롤은 100, -100이라 10, -10으로 조절해서 scale 변경
=> #111 [fix] 차트 줌기능 트랙패드 적용

src/components/CardList/CardList.tsx, src/controllers/api.Type.ts, src/controllers/query.ts
카드리스트 리팩토링
- 타입 지정
- 불필요한 suspend 제거
=> #90 [refactor] 카드리스트 리팩토링

src/components/CardList/CardList.tsx, src/components/CardList/StockCard/StockCard.tsx, src/components/Home/IndexScore/IndexScore.tsx, src/components/Home/Keywords/Keywords.tsx, src/components/Home/StockTable/StockTable.tsx, src/components/Search/SearchTitle/SearchTitle.tsx, src/controllers/api.Type.ts, src/controllers/mock.ts, src/controllers/query.ts, src/pages/Search/Search.tsx
#feat/90 > develop
아래와 같이 수정
// query.ts
export const IndexScoreQuery = () => {
return useQuery<IndexInfo>(['indexScore'], () => fetchIndexScore(), queryOptions);
};
// IndexScore.tsx
const { data: indexScores } = IndexScoreQuery();
=> #90 [refactor] useQuery 리팩토링

src/components/CardList/CardList.tsx, src/components/CardList/StockCard/StockCard.tsx, src/components/Home/IndexScore/IndexScore.tsx, src/components/Home/Keywords/Keywords.tsx, src/components/Home/StockTable/StockTable.tsx, src/components/Search/SearchTitle/SearchTitle.tsx, src/controllers/query.ts, src/pages/Search/Search.tsx
=> #90 [refactor] api쿼리 로직 수정

src/pages/Search/Search.Style.ts, src/pages/Search/Search.tsx
=> #315 [feat] 모의 매수하기 버튼 구현

src/pages/ShortView/ShortView.tsx
=> #315 [FIX] 빌드 오류 해결

src/components/PopUp/PWAinfoPopUp/PWAinfoPopUp.style.ts, src/layout/BottomNavigation/BottomNavigation.Style.ts, src/layout/BottomNavigation/BottomNavigation.tsx
=> #315 [FEAT]: 하단 내비게이션바 개발

package-lock.json, package.json, src/pages/ShortView/ShortView.Style.ts, src/pages/ShortView/ShortView.tsx, yarn.lock
=> #315 [Feat] 숏뷰 틴더카드 라이브러리 도입

src/components/Search/SearchTitle/SearchTitle.tsx, src/components/SearchBar/SearchBar.Style.ts, src/components/SearchBar/SearchBar.tsx, src/layout/BottomNavigation/BottomNavigation.Style.ts, src/layout/Header/Header.Style.ts, src/layout/Header/Header.tsx, src/layout/Mainlayout/Mainlayout.Style.ts, src/layout/Mainlayout/Mainlayout.tsx, src/pages/Home/Home.Style.ts, src/pages/Search/Search.Style.ts, src/pages/ShortView/Advanced.tsx, src/pages/ShortView/ShortView.Style.ts, src/pages/ShortView/ShortView.tsx, src/router/index.tsx
=> #315 [Feat] 숏뷰 구현중

src/layout/BottomNavigation/BottomNavigation.tsx, src/layout/Header/Header.tsx, src/layout/Mainlayout/Mainlayout.tsx, src/pages/Lab/Lab.Style.ts, src/pages/Lab/Lab.tsx, src/pages/ShortView/ShortView.Style.ts, src/router/index.tsx, src/styles/themes.ts
feat/#331 -> dev
실험실 초기 화면 뷰 구현
=> #331 [Feat] 초기 화면 뷰 구현

src/components/Lab/StockSelection/StockSelection.tsx
=> #331 [Feat] 관심 산업 최대 선택 개수 구현

src/pages/Login/Login.tsx
feat/#343-kakao-login -> dev
리다이렉트 url 수정
=> #343 [fix] redirect Url 동적 반영

src/components/Lab/StockSearch/StockSearch.tsx, src/components/Lab/StockSelection/StockSelection.Style.ts, src/layout/BottomNavigation/BottomNavigation.tsx
=> #331 [Feat] 종목검색시 네비게이션바 비활성화

src/components/LabResult/LabResult.tsx
=> #331 [test] UI 테스트용

src/controllers/api/auth.ts, src/pages/Register/Register.tsx
=> #389 [Feat] 로그인 로직 수정

src/controllers/api.Type.ts, src/controllers/api/favorites.ts, src/controllers/query/favorites.ts, src/pages/Favorites/Favorites.Style.ts, src/pages/Favorites/Favorites.tsx
=> Feat/#369 관싱좀목 페이지 API 연동
